workflows:
  android:
    name: Build Android Debug APK
    max_build_duration: 10
    environment:
      flutter: stable
      vars:
        JAVA_VERSION: 17
    scripts:
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

