workflows:
  build-apk:
    name: Build APK and Upload to GitHub
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "build/app/outputs/flutter-apk/app-release.apk"
      groups:
        - github_credentials

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

      - name: Install GitHub CLI (manual install)
        script: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.39.1/gh_2.39.1_linux_amd64.tar.gz -o gh.tar.gz
          tar -xzf gh.tar.gz
          sudo mv gh_2.39.1_linux_amd64/bin/gh /usr/local/bin/

      - name: Authenticate GitHub CLI
        script: |
          echo "$GITHUB_TOKEN" | gh auth login --with-token

      - name: Publish to GitHub Releases
        script: |
          tag_name="v$(date +%Y.%m.%d.%H%M)"
          apk_path="$PACKAGE_NAME"

          echo "Creating GitHub release $tag_name with APK: $apk_path"

          gh release create "$tag_name" "$apk_path" \
            --repo "$GITHUB_REPOSITORY" \
            --title "Codemagic APK Build" \
            --notes "Automatski build i upload .apk datoteke s Codemagica." \
            --target "$FCI_COMMIT"

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
