workflows:
  android:
    name: Build Android
    max_build_duration: 10
    environment:
  vars:
    JAVA_VERSION: 17
    scripts:
      - flutter pub get
      - flutter build appbundle --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
