workflows:
  build-apk:
    name: Build APK and publish to GitHub Releases
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_PATH: build/app/outputs/flutter-apk/app-release.apk
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release
      - name: Install GitHub CLI
        script: |
          brew install gh
      - name: Upload APK to GitHub Releases
        script: |
          set -e
          TAG_NAME=$(git describe --tags --always)
          gh release create "$TAG_NAME" "$PACKAGE_PATH" \
            --title "Build $TAG_NAME" \
            --notes "Automatski build s Codemagica"
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

