workflows:
  build-android-apk:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
