workflows:
  android-release:
    name: Android APK Release
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: flutter build apk --release

      - name: Upload to GitHub Releases
        script: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          TAG_NAME="v$VERSION"
          gh release create "$TAG_NAME" \
            build/app/outputs/flutter-apk/app-release.apk \
            --title "Release $VERSION" \
            --notes "APK release build for version $VERSION"
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
