name: pametnakupnja
description: A new Flutter project.
publish_to: 'none' # Ovo ostavi ako ne planiraš objavljivati na pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Obavezno za iOS/Android ikone
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
